---
- name: "Bash | Ubuntu/WSL only"
  ansible.builtin.assert:
    that:
      - ansible_distribution == 'Ubuntu'
    fail_msg: "This role supports Ubuntu 24.04 (incl. WSL) only."
    success_msg: "Ubuntu detected."
  tags: [bash]

- name: "Bash | Ensure prerequisites (curl, wget, git)"
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - git
    state: present
    update_cache: true
  become: true
  tags: [bash, prereq]

- name: "Bash | Check if Oh My Bash is already installed"
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.oh-my-bash"
  register: omb_dir
  tags: [bash, install]

- name: "Bash | Install Oh My Bash via curl"
  ansible.builtin.shell: >
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.oh-my-bash"
  when:
    - not omb_dir.stat.exists
    - bash_install_method | lower == 'curl'
  changed_when: true
  tags: [bash, install]

- name: "Bash | Install Oh My Bash via wget"
  ansible.builtin.shell: >
    bash -c "$(wget https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh -O -)"
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.oh-my-bash"
  when:
    - not omb_dir.stat.exists
    - bash_install_method | lower == 'wget'
  changed_when: true
  tags: [bash, install]

- name: "Bash | Ensure ~/.bash_profile sources ~/.bashrc"
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bash_profile"
    create: true
    block: |
      if [[ -f ~/.bashrc ]]; then
        source ~/.bashrc
      fi
  tags: [bash, profile]
