---
- name: DotFiles Config
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Detect WSL
      ansible.builtin.import_tasks: pre_tasks/detect_wsl.yml
      tags: [always]

    - name: Debug WSL detection result
      ansible.builtin.debug:
        var: ansible_host_environment_is_wsl
      tags: [always]

    - name: WSL-only Confirm Windows PowerShell Execution Policy
      ansible.builtin.import_tasks: pre_tasks/powershell_executionpolicy.yml
      when: ansible_host_environment_is_wsl | default(false)
      tags: [always]

    - name: WSL-only Detect Host User (Windows user)
      ansible.builtin.import_tasks: pre_tasks/whoami_wsl.yml
      when: ansible_host_environment_is_wsl | default(false)
      tags: [always]

    - name: Detect Host User (Linux user)
      ansible.builtin.import_tasks: pre_tasks/whoami.yml
      tags: [always]

    - name: Detect Sudo
      ansible.builtin.import_tasks: pre_tasks/detect_sudo.yml
      tags: [always]

  tasks:
    - name: Compute roles to run
      ansible.builtin.set_fact:
        run_roles: >-
          {{
            (ansible_run_tags != ['all']
              and ansible_run_tags
              or (default_roles | default([])))
            | difference(exclude_roles | default([]))
            | sort
          }}
      tags: [always]

    - name: Run roles
      ansible.builtin.include_role:
        name: "{{ roles_item }}"
        apply:
          tags: ["{{ roles_item }}"]
      loop: "{{ run_roles }}"
      loop_control:
        loop_var: roles_item
      tags: [always]
