---
- name: Run selected roles
  hosts: localhost
  connection: local
  gather_facts: yes
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Discover available roles in roles/ directory
      ansible.builtin.set_fact:
        available_roles: "{{ lookup('ansible.builtin.fileglob', playbook_dir ~ '/roles/*', wantlist=True) | map('basename') | list }}"
      tags: [always]

    - name: Compute role tags provided by user (excluding special tags)
      ansible.builtin.set_fact:
        user_role_tags: "{{ (ansible_run_tags | difference(['all','always'])) | intersect(available_roles) }}"
      tags: [always]

    - name: Compute roles to run (prefer user tags if any, else defaults)
      ansible.builtin.set_fact:
        run_roles: >-
          {{
            (user_role_tags | length > 0)
              | ternary(user_role_tags, (default_roles | default([])))
            | difference(exclude_roles | default([]))
            | intersect(available_roles)
            | unique
            | sort
          }}
      tags: [always]

    - name: Show resolved roles
      ansible.builtin.debug:
        var: run_roles
      tags: [always]

    - name: Run roles
      ansible.builtin.include_role:
        name: "{{ roles_item }}"
        apply:
          tags: ["{{ roles_item }}"]
      loop: "{{ run_roles }}"
      loop_control:
        loop_var: roles_item
      tags: [always]
